### ISSUE TITLE
Flume stuck

### ISSUE THREAD

**Issue by clehner** [ssbc/ssb-server#427]
I found that my local scuttlebot instance was not responding to queries except whoami.
I deleted ~/.ssb/db and ~/.ssb/flume except for ~/.ssb/flume/log.offset and restarted sbot to let it rebuild indexes. After it finished, I could query sbot. But then when I tried to publish a message or gossip with peers, sbot crashed with this error:
```
************************************************** (indexes:100%, ebt:97.5%)/home/cel/src/scuttlebot/node_modules/aligned-block-file/file.js:52
      if(writing++) throw new Error('already writing to this file')
                    ^

Error: already writing to this file
    at Object.append (/home/cel/src/scuttlebot/node_modules/aligned-block-file/file.js:52:27)
    at next (/home/cel/src/scuttlebot/node_modules/aligned-block-file/blocks.js:167:16)
    at /home/cel/src/scuttlebot/node_modules/aligned-block-file/blocks.js:138:18
    at get (/home/cel/src/scuttlebot/node_modules/aligned-block-file/blocks.js:28:7)
    at /home/cel/src/scuttlebot/node_modules/aligned-block-file/blocks.js:136:11
    at Function.many.once (/home/cel/src/scuttlebot/node_modules/obv/index.js:38:49)
    at Object.append (/home/cel/src/scuttlebot/node_modules/aligned-block-file/blocks.js:130:19)
    at /home/cel/src/scuttlebot/node_modules/flumelog-offset/inject.js:27:14
    at Function.many.once (/home/cel/src/scuttlebot/node_modules/obv/index.js:38:49)
    at /home/cel/src/scuttlebot/node_modules/flumelog-offset/inject.js:21:11
```

`status` shows plugins are not up to `since`, so I think this means flume is stuck:

```
$ sbot status|jq .
{
  "progress": {
    "indexes": {
      "start": 64915634,
      "current": 119011996,
      "target": 119008187
    }
  },
  "sync": {
    "since": 119008187,
    "plugins": {
      "last": 119011996,
      "keys": 119011996,
      "clock": 119011996,
      "feed": 119011996,
      "time": 119011996,
      "friends": 119011996,
      "query": 119011996,
      "links2": 119011996,
      "backlinks-f_6sQ6d2C": 119011996,
      "about": 119011996,
      "contacts": 119011996
    },
    "sync": false
  },
  "gossip": {},
  "ebt": {}
}
```

scuttlebot@4820e757662c2b72a8bd6d27c83c9afd2a5c354e v10.4.2

Output of `npm ls`:
https://celehner.com/ebt-err-paste.txt

I tried moving away the db again and got the same error and stuck behavior.

@dominictarr Any ideas?

**Comment by dominictarr** [comment]
the plugins are _ahead_ of the log!!! that isn't right `119008187 < 119011996` !?

does `sbot get 119008187` and `sbot get 119011996` return anything?

**Comment by dominictarr** [comment]
is your instance currently broken? does restarting help?

my hunch is that an append isn't happening right, like maybe a throw in the callback or something?

**Comment by clehner** [comment]
i have temporarily lost access to my usual computing environment, so i 
am unable to continue testing at this point.

**Comment by clehner** [comment]
migrated the log.offset file to a new machine & scuttlebot installation, 
and am getting the same problem. i think i will try resyncing the log

$ sbotc status | jq .
{
  "progress": {
    "indexes": {
      "start": 74377312,
      "current": 119003700,
      "target": 119000978
    }
  },
  "sync": {
    "since": 119000978,
    "plugins": {
      "last": 119003700,
      "keys": 119003700,
      "clock": 119003700,
      "feed": 119003700,
      "time": 119003700,
      "friends": 119003700,
      "query": 119003700,
      "links2": 119003700
    },
    "sync": false
  },
  "gossip": {}
}

$ sbotc get 119000978
{"key":"%6JDgOaDyNVvc7lXtQgujXXIDBf+VbKCzhLT40ul3e5A=.sha256","value":{"previous":"%Lyyz5LAhWCjHzXvDq01S9CUJhxfGBjaw0oc4tR65UHE=.sha256","author":"@ye+QM09iPcDJD6YvQYjoQc
7sLF/IFhmNbEqgdzQo3lQ=.ed25519","sequence":7823,"timestamp":1500414566291,"hash":"sha256","content":"Aqu9ImYJadtP7igQlQJ+G7dCnae/HeOCJyHQWWKJLye8CIYLk5YFuZ+tkYgS1OW3XZ9Zu
at9OGfAJehvS0ABHO+IYYwkgRm+TOs9vTNpX8SEsBpLpPxGve78nr+XF2MCpp7lY1s7iW0XWxl72rNHZ7zHv+C+4b0CdF2wF8vJF1wgmPYxRte7W3b6Usk6DRrJorQJoKM0/AKqe33MjyNOPwhj8R1prfVS6i/wW28F5DbKM0a
NWOOccQgPTdgb3V+Fk9h7wMTIMpCMtlQtuQevf4CKCvDI+shz5OWO4QFIs9Nn3NyMv3dZAqEbq4nq3k7mv8TwRe0H1CKhGzSPkW2uaaSCLi1+b0/cuyM8iqWfiQJS7Ff5XpsejCJl1SYc0xhwyy6wFhYjYFBQ6LfW1y0XJCGHh
pKsdNsQl40q49+p//j31WkfYzgcFKdLRdUq5V55LDL6yc0hcQDuciFgjZFfgBvfIs7drEfchEbmbN2gCnwvSkadyOom5Y8tUQK6a1yzd3ji7+2FxcCKpX+gXTygcfVTQiF0baSG5Ye1XhsfV8AVXbWdW0/Ox13peennwRiB4NW
blVBG6FaFbcAo3m9HWCksxXlISTXLDcHSNY96Ig8Kt4hQOrl65HTq65ymI5t5FdIFTbRRlLPYtV/iVm/q9+G5j7n+nDiJdHG0yHL1uAGGN5PA4ncVlQm/91YXQVZlviUW7Bd8qv1Sg2HJaynTEkGc08vZSj3jCFcflXS/k1/kf
8ngIUffjq/0njYVZN2Nnc0Arl1DzTndQIsmFpUSszKjA5SlxPikKsbxzwEYfXYGto+qCuavLpEY96N3HJOURIBjFHitbd8EYtMC+UGlA6tIi9kECQ2HauXzjSJsPzqIV9eC84o0h0FhN8Lv6f8hq+ezKqqRZxNP2lzqcLrmXRC
9kAlGTfGvCueTN0WtBqlWvdUkyeZcFmBqpMsQ0LZ76N6dBjdqAG6mM50qsZisicEqaIflp3blnFA5Z7KocDydXCtEBWRBvSMIU/Bg/S+aIZv80RIWX8ssKRVHe2EKnMCDLgMsa2EMg94KtFbsNGgfqqbPRkvvPwydR9k3Bbzv5
oavBF+cynKo7za5TblJSVxgpQKnXmaDldgx32KaXRebNU6IPUw0mnJP1hb2GkhcWuGCfUlMvSxiButQ7eI5/PIEadOEUbhr/yuJDWXuz+FdHymLd5rEf7R5Sg==.box","signature":"RwLYcC/1dMY9WyyfS4nLxbl9tNQJ
Fq1ZMYfMm0Z2z0ywPGs2pugt/bahWcGM1TftHnpDUK24re9F99dhBQQ3Cw==.sig.ed25519"},"timestamp":1500414583376}

$ sbot get 119003700

/home/cel/node_modules/muxrpcli/index.js:68
      throw err
      ^
Error: past end
    at Object.read 
(/home/cel/node_modules/aligned-block-file/blocks.js:47:17)
    at next 
(/home/cel/node_modules/flumelog-offset/frame/recoverable.js:39:16)
    at /home/cel/node_modules/flumelog-offset/frame/recoverable.js:35:11
    at /home/cel/node_modules/aligned-block-file/blocks.js:93:11
    at get (/home/cel/node_modules/aligned-block-file/blocks.js:28:7)
    at Object.readUInt32BE 
(/home/cel/node_modules/aligned-block-file/blocks.js:90:9)
    at /home/cel/node_modules/flumelog-offset/frame/recoverable.js:33:16
    at /home/cel/node_modules/aligned-block-file/blocks.js:93:11
    at get (/home/cel/node_modules/aligned-block-file/blocks.js:28:7)
    at Object.readUInt32BE 
(/home/cel/node_modules/aligned-block-file/blocks.js:90:9)

**Comment by dominictarr** [comment]
can post `tail -c 1000 ~/.ssb/flume/log.offset | hexdump -C` ?

**Comment by clehner** [comment]
$ tail -c 1000 ~/.ssb/old/flume/log.offset | hexdump -C

00000000  37 46 66 35 58 70 73 65  6a 43 4a 6c 31 53 59 63  
|7Ff5XpsejCJl1SYc|
00000010  30 78 68 77 79 79 36 77  46 68 59 6a 59 46 42 51  
|0xhwyy6wFhYjYFBQ|
00000020  36 4c 66 57 31 79 30 58  4a 43 47 48 68 70 4b 73  
|6LfW1y0XJCGHhpKs|
00000030  64 4e 73 51 6c 34 30 71  34 39 2b 70 2f 2f 6a 33  
|dNsQl40q49+p//j3|
00000040  31 57 6b 66 59 7a 67 63  46 4b 64 4c 52 64 55 71  
|1WkfYzgcFKdLRdUq|
00000050  35 56 35 35 4c 44 4c 36  79 63 30 68 63 51 44 75  
|5V55LDL6yc0hcQDu|
00000060  63 69 46 67 6a 5a 46 66  67 42 76 66 49 73 37 64  
|ciFgjZFfgBvfIs7d|
00000070  72 45 66 63 68 45 62 6d  62 4e 32 67 43 6e 77 76  
|rEfchEbmbN2gCnwv|
00000080  53 6b 61 64 79 4f 6f 6d  35 59 38 74 55 51 4b 36  
|SkadyOom5Y8tUQK6|
00000090  61 31 79 7a 64 33 6a 69  37 2b 32 46 78 63 43 4b  
|a1yzd3ji7+2FxcCK|
000000a0  70 58 2b 67 58 54 79 67  63 66 56 54 51 69 46 30  
|pX+gXTygcfVTQiF0|
000000b0  62 61 53 47 35 59 65 31  58 68 73 66 56 38 41 56  
|baSG5Ye1XhsfV8AV|
000000c0  58 62 57 64 57 30 2f 4f  78 31 33 70 65 65 6e 6e  
|XbWdW0/Ox13peenn|
000000d0  77 52 69 42 34 4e 57 62  6c 56 42 47 36 46 61 46  
|wRiB4NWblVBG6FaF|
000000e0  62 63 41 6f 33 6d 39 48  57 43 6b 73 78 58 6c 49  
|bcAo3m9HWCksxXlI|
000000f0  53 54 58 4c 44 63 48 53  4e 59 39 36 49 67 38 4b  
|STXLDcHSNY96Ig8K|
00000100  74 34 68 51 4f 72 6c 36  35 48 54 71 36 35 79 6d  
|t4hQOrl65HTq65ym|
00000110  49 35 74 35 46 64 49 46  54 62 52 52 6c 4c 50 59  
|I5t5FdIFTbRRlLPY|
00000120  74 56 2f 69 56 6d 2f 71  39 2b 47 35 6a 37 6e 2b  
|tV/iVm/q9+G5j7n+|
00000130  6e 44 69 4a 64 48 47 30  79 48 4c 31 75 41 47 47  
|nDiJdHG0yHL1uAGG|
00000140  4e 35 50 41 34 6e 63 56  6c 51 6d 2f 39 31 59 58  
|N5PA4ncVlQm/91YX|
00000150  51 56 5a 6c 76 69 55 57  37 42 64 38 71 76 31 53  
|QVZlviUW7Bd8qv1S|
00000160  67 32 48 4a 61 79 6e 54  45 6b 47 63 30 38 76 5a  
|g2HJaynTEkGc08vZ|
00000170  53 6a 33 6a 43 46 63 66  6c 58 53 2f 6b 31 2f 6b  
|Sj3jCFcflXS/k1/k|
00000180  66 38 6e 67 49 55 66 66  6a 71 2f 30 6e 6a 59 56  
|f8ngIUffjq/0njYV|
00000190  5a 4e 32 4e 6e 63 30 41  72 6c 31 44 7a 54 6e 64  
|ZN2Nnc0Arl1DzTnd|
000001a0  51 49 73 6d 46 70 55 53  73 7a 4b 6a 41 35 53 6c  
|QIsmFpUSszKjA5Sl|
000001b0  78 50 69 6b 4b 73 62 78  7a 77 45 59 66 58 59 47  
|xPikKsbxzwEYfXYG|
000001c0  74 6f 2b 71 43 75 61 76  4c 70 45 59 39 36 4e 33  
|to+qCuavLpEY96N3|
000001d0  48 4a 4f 55 52 49 42 6a  46 48 69 74 62 64 38 45  
|HJOURIBjFHitbd8E|
000001e0  59 74 4d 43 2b 55 47 6c  41 36 74 49 69 39 6b 45  
|YtMC+UGlA6tIi9kE|
000001f0  43 51 32 48 61 75 58 7a  6a 53 4a 73 50 7a 71 49  
|CQ2HauXzjSJsPzqI|
00000200  56 39 65 43 38 34 6f 30  68 30 46 68 4e 38 4c 76  
|V9eC84o0h0FhN8Lv|
00000210  36 66 38 68 71 2b 65 7a  4b 71 71 52 5a 78 4e 50  
|6f8hq+ezKqqRZxNP|
00000220  32 6c 7a 71 63 4c 72 6d  58 52 43 39 6b 41 6c 47  
|2lzqcLrmXRC9kAlG|
00000230  54 66 47 76 43 75 65 54  4e 30 57 74 42 71 6c 57  
|TfGvCueTN0WtBqlW|
00000240  76 64 55 6b 79 65 5a 63  46 6d 42 71 70 4d 73 51  
|vdUkyeZcFmBqpMsQ|
00000250  30 4c 5a 37 36 4e 36 64  42 6a 64 71 41 47 36 6d  
|0LZ76N6dBjdqAG6m|
00000260  4d 35 30 71 73 5a 69 73  69 63 45 71 61 49 66 6c  
|M50qsZisicEqaIfl|
00000270  70 33 62 6c 6e 46 41 35  5a 37 4b 6f 63 44 79 64  
|p3blnFA5Z7KocDyd|
00000280  58 43 74 45 42 57 52 42  76 53 4d 49 55 2f 42 67  
|XCtEBWRBvSMIU/Bg|
00000290  2f 53 2b 61 49 5a 76 38  30 52 49 57 58 38 73 73  
|/S+aIZv80RIWX8ss|
000002a0  4b 52 56 48 65 32 45 4b  6e 4d 43 44 4c 67 4d 73  
|KRVHe2EKnMCDLgMs|
000002b0  61 32 45 4d 67 39 34 4b  74 46 62 73 4e 47 67 66  
|a2EMg94KtFbsNGgf|
000002c0  71 71 62 50 52 6b 76 76  50 77 79 64 52 39 6b 33  
|qqbPRkvvPwydR9k3|
000002d0  42 62 7a 76 35 6f 61 76  42 46 2b 63 79 6e 4b 6f  
|Bbzv5oavBF+cynKo|
000002e0  37 7a 61 35 54 62 6c 4a  53 56 78 67 70 51 4b 6e  
|7za5TblJSVxgpQKn|
000002f0  58 6d 61 44 6c 64 67 78  33 32 4b 61 58 52 65 62  
|XmaDldgx32KaXReb|
00000300  4e 55 36 49 50 55 77 30  6d 6e 4a 50 31 68 62 32  
|NU6IPUw0mnJP1hb2|
00000310  47 6b 68 63 57 75 47 43  66 55 6c 4d 76 53 78 69  
|GkhcWuGCfUlMvSxi|
00000320  42 75 74 51 37 65 49 35  2f 50 49 45 61 64 4f 45  
|ButQ7eI5/PIEadOE|
00000330  55 62 68 72 2f 79 75 4a  44 57 58 75 7a 2b 46 64  
|Ubhr/yuJDWXuz+Fd|
00000340  48 79 6d 4c 64 35 72 45  66 37 52 35 53 67 3d 3d  
|HymLd5rEf7R5Sg==|
00000350  2e 62 6f 78 22 2c 22 73  69 67 6e 61 74 75 72 65  
|.box","signature|
00000360  22 3a 22 52 77 4c 59 63  43 2f 31 64 4d 59 39 57  
|":"RwLYcC/1dMY9W|
00000370  79 79 66 53 34 6e 4c 78  62 6c 39 74 4e 51 4a 46  
|yyfS4nLxbl9tNQJF|
00000380  71 31 5a 4d 59 66 4d 6d  30 5a 32 7a 30 79 77 50  
|q1ZMYfMm0Z2z0ywP|
00000390  47 73 32 70 75 67 74 2f  62 61 68 57 63 47 4d 31  
|Gs2pugt/bahWcGM1|
000003a0  54 66 74 48 6e 70 44 55  4b 32 34 72 65 39 46 39  
|TftHnpDUK24re9F9|
000003b0  39 64 68 42 51 51 33 43  77 3d 3d 2e 73 69 67 2e  
|9dhBQQ3Cw==.sig.|
000003c0  65 64 32 35 35 31 39 22  7d 2c 22 74 69 6d 65 73  
|ed25519"},"times|
000003d0  74 61 6d 70 22 3a 31 35  30 30 34 31 34 35 38 33  
|tamp":1500414583|
000003e0  33 37 36 7d 00 00 06 5f                           |376}..._|
000003e8

**Comment by dominictarr** [comment]
okay, that is a valid end... some how the views have a message that is newer than the one in the log which is very strange. I mean, that should definitely never happen. but I guess maybe it could have made it into the log but then a restart wiped it or something? what we could just do is check if any views are ahead of the log and if so, rebuild those views?

hmm, but didn't you say this still happened if you rebuilt the views?

**Comment by clehner** [comment]
> but didn't you say this still happened if you rebuilt the views?

right. since i got it working after resync though, i'm okay to leave this 
be. i'll hold onto the old log.offset file in case we want it for debugging 
later.

**Comment by dominictarr** [comment]
If I can use the old log to reproduce it that would be great - you know enough ssb to get it working again, but for many people they might just give up.

**Comment by clehner** [comment]
Ok, I will upload the log file and send you a link.

**Comment by Juul** [comment]
I believe I am repeatedly having the same issue. `sbot` only gives any output on `whoami` and otherwise hangs giving no output. Every time I have this issue it has been fixed by deleting `~/.ssb/flumedb` and waiting for the upgrade/download to complete. It's happening to me every few days at this point. This has been happening to at least two other people on the sudomesh team. I looked at the flumelog-level code a bit but unfortunately I don't really have time to dig deeply into this. @dominictarr would sending you my `~/.ssb/` without my secrets file help?

**Comment by evbogue** [comment]
I got hit by this one two days ago, gb's computer was hit by it yesterday. I get the same issue as @Juul, only get output on `whoami` command. No errors. Toasting my flumedb and regenerating solves the issue.

What I don't get is why is this just hitting me now? I've been using flume for a long time.

**Comment by Juul** [comment]
It seems to appear more often when scuttlebot is not shut down properly,
e.g. when my laptop battery dies. I sent dominic a copy of my broken
flumedb yesterday and he has already made some progress in tracking down
this bug.

**Comment by dominictarr** [comment]
question: what sort of laptop hard drives do you have?

check `sbot status` when this happens and post output of the `sync` section.

**Comment by Juul** [comment]
On Sat, Oct 14, 2017 at 12:32 PM, Dominic Tarr <notifications@github.com>
wrote:

> question: what sort of laptop hard drives do you have?
>
An SSD with normal luks full disk encryption and then ext4. No LVM.

-- 
marc/juul

**Comment by dominictarr** [comment]
this should be fixed if you update to latest scuttlebot.
by the way, I realized this isn't about write speed at all, at some point the log is half written (because of powerloss) but then there was a bug in the recovery code that recorrupted it again, which then rerecovered it again leaving the views ahead, which then bricked it. fixed both bugs, so just updating the code and running should fix everything.

**Comment by evbogue** [comment]
This issue isn't quite resolved, so I'm reopening. It seems that `flumeview-query` contains an out-of-date version of `flumeview-level` that calls an incorrect `level.destroy()` to regenerate the index. 

I had an unexpected poweroff which revealed this to me. 

I'm trying to upgrade `flumeview-query` but now it's not passing tests... working on it.

**Comment by evbogue** [comment]
ok, after messing around with this for 30 minutes I officially concede I am in over my head on this. Aborting! cc @dominictarr

**Comment by dominictarr** [comment]
@evbogue but tell us what you tried! what output etc

**Comment by evbogue** [comment]
@dominictarr I tried updating `flumeview-level` within `flumeview-query` to latest, and then I began getting this when running `npm test`

```
/home/ev/flumeview-query/node_modules/map-filter-reduce/index.js:27
    return data.sync ? data : fn(data)
                ^

TypeError: Cannot read property 'sync' of undefined
    at /home/ev/flumeview-query/node_modules/map-filter-reduce/index.js:27:17
    at /home/ev/flumeview-query/node_modules/pull-stream/throughs/filter.js:15:23
    at /home/ev/flumeview-query/node_modules/pull-stream/throughs/map.js:19:9
    at /home/ev/flumeview-query/node_modules/pull-stream/throughs/map.js:19:9
    at /home/ev/flumeview-query/node_modules/pull-stream/throughs/filter.js:17:11
    at drain (/home/ev/flumeview-query/node_modules/stream-to-pull-stream/index.js:141:18)
    at ReadStream.<anonymous> (/home/ev/flumeview-query/node_modules/stream-to-pull-stream/index.js:150:5)
    at emitOne (events.js:115:13)
    at ReadStream.emit (events.js:210:7)
    at readableAddChunk (/home/ev/flumeview-query/node_modules/readable-stream/lib/_stream_readable.js:195:16)
```

That point I realized I don't know enough about flumedb and it's associated parts to know how to fix this.

**Comment by evbogue** [comment]
The reason I had this error was because the sbot in question hadn't been updated. I think if it had been running the latest version of secure-scuttlebutt, I would have been fine and not had to regenerate. 

I can't confirm or deny whether 'flume stuck' is still happening on latest, but what I do know is the regeneration of the db isn't working.

**Comment by dominictarr** [comment]
okay, hmm, another good technique, is check out older commits to see at what point it broke exactly.
I clone the test module into your dev directory, then symlink it from the other node_modules

so it's like
```
flumeview-level
flumeview-query/node_modules/flumeview-level -> ../../flumeview-level
```

then you can check out older versions of flumeview-level and see where it breaks the flumeview-query tests exactly.

**Comment by dominictarr** [comment]
...then just `git diff master` from that commit and see what has changed

**Comment by uhlhosting** [comment]
```
/usr/local/lib/node_modules/scuttlebot/node_modules/muxrpcli/index.js:68
      throw err
      ^
Error: aligned-block-file/file.get: requested block index was greater than max, got:7263, expected less than or equal to:0
    at /Applications/Patchwork.app/Contents/Resources/app.asar/node_modules/aligned-block-file/file.js:27:21
    at Function.many.once (/Applications/Patchwork.app/Contents/Resources/app.asar/node_modules/aligned-block-file/node_modules/obv/index.js:38:49)
    at Object.get (/Applications/Patchwork.app/Contents/Resources/app.asar/node_modules/aligned-block-file/file.js:24:14)
    at get (/Applications/Patchwork.app/Contents/Resources/app.asar/node_modules/aligned-block-file/blocks.js:33:12)
    at Object.readUInt32BE (/Applications/Patchwork.app/Contents/Resources/app.asar/node_modules/aligned-block-file/blocks.js:90:9)
    at Object.getMeta (/Applications/Patchwork.app/Contents/Resources/app.asar/node_modules/flumelog-offset/frame/recoverable.js:31:12)
    at Object.get (/Applications/Patchwork.app/Contents/Resources/app.asar/node_modules/flumelog-offset/inject.js:78:13)
    at Object.get (/Applications/Patchwork.app/Contents/Resources/app.asar/node_modules/flumedb/index.js:30:10)
    at /Applications/Patchwork.app/Contents/Resources/app.asar/node_modules/flumedb/index.js:55:13
    at Function.many.once (/Applications/Patchwork.app/Contents/Resources/app.asar/node_modules/obv/index.js:39:7)
cosmicsound@mdb:~$ tail -c 1000 ~/.ssb/flume/log.offset | hexdump -C
00000000  3a 7b 22 70 72 65 76 69  6f 75 73 22 3a 6e 75 6c  |:{"previous":nul|
00000010  6c 2c 22 61 75 74 68 6f  72 22 3a 22 40 37 6c 72  |l,"author":"@7lr|
00000020  7a 58 56 70 69 56 6f 50  45 6d 2f 49 31 4e 42 61  |zXVpiVoPEm/I1NBa|
00000030  4e 6b 4b 79 51 50 6e 6c  71 7a 4b 4c 39 36 67 4b  |NkKyQPnlqzKL96gK|
00000040  43 69 6e 56 77 4e 41 55  3d 2e 65 64 32 35 35 31  |CinVwNAU=.ed2551|
00000050  39 22 2c 22 73 65 71 75  65 6e 63 65 22 3a 31 2c  |9","sequence":1,|
00000060  22 74 69 6d 65 73 74 61  6d 70 22 3a 31 35 30 39  |"timestamp":1509|
00000070  34 32 35 34 35 33 37 32  34 2c 22 68 61 73 68 22  |425453724,"hash"|
00000080  3a 22 73 68 61 32 35 36  22 2c 22 63 6f 6e 74 65  |:"sha256","conte|
00000090  6e 74 22 3a 7b 22 74 79  70 65 22 3a 22 61 62 6f  |nt":{"type":"abo|
000000a0  75 74 22 2c 22 61 62 6f  75 74 22 3a 22 40 37 6c  |ut","about":"@7l|
000000b0  72 7a 58 56 70 69 56 6f  50 45 6d 2f 49 31 4e 42  |rzXVpiVoPEm/I1NB|
000000c0  61 4e 6b 4b 79 51 50 6e  6c 71 7a 4b 4c 39 36 67  |aNkKyQPnlqzKL96g|
000000d0  4b 43 69 6e 56 77 4e 41  55 3d 2e 65 64 32 35 35  |KCinVwNAU=.ed255|
000000e0  31 39 22 2c 22 6e 61 6d  65 22 3a 22 63 73 6d 64  |19","name":"csmd|
000000f0  62 22 2c 22 64 65 73 63  72 69 70 74 69 6f 6e 22  |b","description"|
00000100  3a 22 43 6f 73 6d 69 63  20 4d 61 73 68 20 44 6f  |:"Cosmic Mash Do|
00000110  77 6e 20 42 61 62 79 6c  6f 6e 22 7d 2c 22 73 69  |wn Babylon"},"si|
00000120  67 6e 61 74 75 72 65 22  3a 22 61 69 32 39 65 52  |gnature":"ai29eR|
00000130  75 38 69 48 6e 4a 72 68  62 78 34 74 4e 38 76 55  |u8iHnJrhbx4tN8vU|
00000140  42 6e 48 51 69 4f 48 63  6e 6d 74 4b 6b 6f 4b 42  |BnHQiOHcnmtKkoKB|
00000150  45 4b 4c 71 35 51 59 76  4d 46 63 4b 57 5a 4a 36  |EKLq5QYvMFcKWZJ6|
00000160  32 6e 44 6f 6f 7a 32 4e  58 4d 5a 56 69 4e 70 74  |2nDooz2NXMZViNpt|
00000170  74 72 65 2b 36 77 54 57  2b 38 6a 61 44 58 43 51  |tre+6wTW+8jaDXCQ|
00000180  3d 3d 2e 73 69 67 2e 65  64 32 35 35 31 39 22 7d  |==.sig.ed25519"}|
00000190  2c 22 74 69 6d 65 73 74  61 6d 70 22 3a 31 35 30  |,"timestamp":150|
000001a0  39 34 32 35 34 35 33 37  32 37 7d 00 00 01 f0 00  |9425453727}.....|
000001b0  00 01 fc 00 00 02 29 7b  22 6b 65 79 22 3a 22 25  |......){"key":"%|
000001c0  44 66 34 41 50 7a 55 70  61 39 44 39 49 32 33 42  |Df4APzUpa9D9I23B|
000001d0  45 64 74 57 31 55 42 70  38 4a 31 58 48 64 41 6f  |EdtW1UBp8J1XHdAo|
000001e0  51 77 70 58 46 52 77 6d  44 6a 30 3d 2e 73 68 61  |QwpXFRwmDj0=.sha|
000001f0  32 35 36 22 2c 22 76 61  6c 75 65 22 3a 7b 22 70  |256","value":{"p|
00000200  72 65 76 69 6f 75 73 22  3a 22 25 6b 49 4c 51 2f  |revious":"%kILQ/|
00000210  59 6a 33 4e 4f 55 51 37  66 43 5a 6c 6c 31 57 31  |Yj3NOUQ7fCZll1W1|
00000220  4a 75 45 6d 78 78 67 59  78 5a 78 79 59 76 74 53  |JuEmxxgYxZxyYvtS|
00000230  6c 2b 6b 4c 36 51 3d 2e  73 68 61 32 35 36 22 2c  |l+kL6Q=.sha256",|
00000240  22 61 75 74 68 6f 72 22  3a 22 40 37 6c 72 7a 58  |"author":"@7lrzX|
00000250  56 70 69 56 6f 50 45 6d  2f 49 31 4e 42 61 4e 6b  |VpiVoPEm/I1NBaNk|
00000260  4b 79 51 50 6e 6c 71 7a  4b 4c 39 36 67 4b 43 69  |KyQPnlqzKL96gKCi|
00000270  6e 56 77 4e 41 55 3d 2e  65 64 32 35 35 31 39 22  |nVwNAU=.ed25519"|
00000280  2c 22 73 65 71 75 65 6e  63 65 22 3a 32 2c 22 74  |,"sequence":2,"t|
00000290  69 6d 65 73 74 61 6d 70  22 3a 31 35 30 39 34 32  |imestamp":150942|
000002a0  35 35 34 36 34 34 38 2c  22 68 61 73 68 22 3a 22  |5546448,"hash":"|
000002b0  73 68 61 32 35 36 22 2c  22 63 6f 6e 74 65 6e 74  |sha256","content|
000002c0  22 3a 7b 22 74 79 70 65  22 3a 22 61 62 6f 75 74  |":{"type":"about|
000002d0  22 2c 22 61 62 6f 75 74  22 3a 22 40 37 6c 72 7a  |","about":"@7lrz|
000002e0  58 56 70 69 56 6f 50 45  6d 2f 49 31 4e 42 61 4e  |XVpiVoPEm/I1NBaN|
000002f0  6b 4b 79 51 50 6e 6c 71  7a 4b 4c 39 36 67 4b 43  |kKyQPnlqzKL96gKC|
00000300  69 6e 56 77 4e 41 55 3d  2e 65 64 32 35 35 31 39  |inVwNAU=.ed25519|
00000310  22 2c 22 69 6d 61 67 65  22 3a 22 26 68 6b 47 73  |","image":"&hkGs|
00000320  43 35 66 6c 67 55 61 45  52 4f 53 35 4a 55 6f 38  |C5flgUaEROS5JUo8|
00000330  4b 58 75 46 6b 4c 4e 6d  4d 4a 70 2f 61 4b 52 6b  |KXuFkLNmMJp/aKRk|
00000340  4d 53 35 6c 30 38 73 3d  2e 73 68 61 32 35 36 22  |MS5l08s=.sha256"|
00000350  7d 2c 22 73 69 67 6e 61  74 75 72 65 22 3a 22 6f  |},"signature":"o|
00000360  78 51 55 6c 53 71 41 55  68 4d 79 61 4b 70 30 68  |xQUlSqAUhMyaKp0h|
00000370  55 4b 75 2f 4f 43 2b 74  6b 79 34 6c 37 63 44 52  |UKu/OC+tky4l7cDR|
00000380  67 47 58 77 4b 66 4e 69  61 70 72 38 2f 50 35 6d  |gGXwKfNiapr8/P5m|
00000390  78 77 50 79 4e 42 37 75  30 36 51 70 4b 64 69 54  |xwPyNB7u06QpKdiT|
000003a0  73 53 51 4f 6d 34 32 76  58 49 75 6a 52 69 36 46  |sSQOm42vXIujRi6F|
000003b0  53 48 73 41 41 3d 3d 2e  73 69 67 2e 65 64 32 35  |SHsAA==.sig.ed25|
000003c0  35 31 39 22 7d 2c 22 74  69 6d 65 73 74 61 6d 70  |519"},"timestamp|
000003d0  22 3a 31 35 30 39 34 32  35 35 34 36 34 35 30 7d  |":1509425546450}|
000003e0  00 00 02 29 00 00 04 31                           |...)...1|
000003e8
cosmicsound@mdb:~$
```

**Comment by gwenbell** [comment]
I'm on the latest version of scuttlebot, this is the error I get this morning. For reference, my laptop powered off mid-sync.
```
 ~/scuttlebot> node bin server
Log level: notice
RELOAD 2 154813440
0 262152 65536 262152
262152 786448 131072 524296
786448 1835032 262144 1048584
RELOADED 154813440
.................................................. (indexes:0%)/home/g/scuttlebot/node_modules/flumeview-query/node_modules/flumeview-level/index.js:36
        level.destroy(db, function () {
        ^

ReferenceError: level is not defined
    at /home/g/scuttlebot/node_modules/flumeview-query/node_modules/flumeview-level/index.js:36:9
    at /home/g/scuttlebot/node_modules/level-packager/node_modules/levelup/lib/levelup.js:136:32
    at /home/g/scuttlebot/node_modules/leveldown/node_modules/abstract-leveldown/abstract-leveldown.js:65:7
```

**Comment by mmckegg** [comment]
@gwenbell looks like for some reason your client is using an old version of [flumeview-level](https://github.com/flumedb/flumeview-level). This was fixed in v2.0.3

@dominictarr Oh I found out why! `flumeview-query` is still depending on `flumeview-level@^1.0.3`. I upgraded it in my "forked" version in ssb-backlinks etc, but this never found its way back to flumeview-query.

**Comment by gwenbell** [comment]
@mmckegg testing now. This is using your branch of flumeview-query.

```
node bin server
Log level: notice
.................................................. (indexes:0%)RELOAD 2 154813440
0 262152 65536 262152
262152 786448 131072 524296
786448 1835032 262144 1048584
RELOADED 154813440
*................................................. (indexes:0%)/home/g/scuttlebot/node_modules/pull-stream/sinks/drain.js:22
                throw end
                ^

Error: iterator has ended
    at Iterator._next (/home/g/scuttlebot/node_modules/leveldown/iterator.js:51:18)
    at Iterator.AbstractIterator.next (/home/g/scuttlebot/node_modules/leveldown/node_modules/abstract-leveldown/abstract-iterator.js:22:17)
    at ReadStream._read (/home/g/scuttlebot/node_modules/level-iterator-stream/index.js:25:18)
    at ReadStream.Readable.read (/home/g/scuttlebot/node_modules/readable-stream/lib/_stream_readable.js:362:10)
    at ReadStream.<anonymous> (/home/g/scuttlebot/node_modules/readable-stream/lib/_stream_readable.js:785:45)
    at emitNone (events.js:105:13)
    at ReadStream.emit (events.js:207:7)
    at emitReadable_ (/home/g/scuttlebot/node_modules/readable-stream/lib/_stream_readable.js:448:10)
    at emitReadable (/home/g/scuttlebot/node_modules/readable-stream/lib/_stream_readable.js:444:5)
    at readableAddChunk (/home/g/scuttlebot/node_modules/readable-stream/lib/_stream_readable.js:187:9)
```

**Comment by dominictarr** [comment]
> I upgraded it in my "forked" version in ssb-backlinks etc, but this never found its way back to flumeview-query.

I told you so!

**Comment by mmckegg** [comment]
@gwenbell I just tried out my fork on my local (non-corrupt) sbot and it seems to be working fine. I suspect that latest error might be another symptom of the corruption 😢 

@dominictarr any ideas what's causing that `iterator has ended` error?

**Comment by gwenbell** [comment]
I tried to regenerate from scratch & now I'm getting this

```
/home/g/flumeview-query/node_modules/map-filter-reduce/index.js:27
    return data.sync ? data : fn(data)

TypeError: Cannot read property 'sync' of undefined
    at /home/g/flumeview-query/node_modules/map-filter-reduce/index.js:27:17
    at /home/g/flumeview-query/node_modules/pull-stream/throughs/filter.js:15:23
    at /home/g/flumeview-query/node_modules/pull-stream/throughs/map.js:19:9
    at /home/g/flumeview-query/node_modules/pull-stream/throughs/map.js:19:9
    at /home/g/flumeview-query/node_modules/pull-stream/throughs/filter.js:17:11
    at /home/g/flumeview-query/node_modules/pull-cat/index.js:35:13
    at drain (/home/g/flumeview-query/node_modules/stream-to-pull-stream/index.js:141:18)
    at ReadStream.<anonymous> (/home/g/flumeview-query/node_modules/stream-to-pull-stream/index.js:150:5)
    at emitOne (events.js:115:13)
    at ReadStream.emit (events.js:210:7)
Log level: notice
.................................................. (indexes:0%)RELOAD 2 74905039
0 262152 65536 262152
262152 786448 131072 524296
786448 1835032 262144 1048584
RELOADED 74905039
/home/g/flumeview-query/node_modules/map-filter-reduce/index.js:27
    return data.sync ? data : fn(data)
```

**Comment by gwenbell** [comment]
Update:

I was running out-of-date software because the package.lock file was for the old version of scuttlebot. Matt was right. 

Now, I am running the newest version of everything. Occasionally this pops up before quitting out:

```
TypeError: Cannot read property '0' of undefined
    at isCloser (/home/g/scuttlebot/node_modules/ssb-friends/block.js:16:10)
    at Object.exports.update (/home/g/scuttlebot/node_modules/ssb-friends/block.js:23:6)
    at Object.exports.diffReachable (/home/g/scuttlebot/node_modules/ssb-friends/alg.js:81:12)
    at /home/g/scuttlebot/node_modules/ssb-friends/index.js:94:25
    at /home/g/scuttlebot/node_modules/pull-flatmap/index.js:10:17
    at /home/g/scuttlebot/node_modules/pull-stream/throughs/filter.js:17:11
    at /home/g/scuttlebot/node_modules/pull-stream/throughs/through.js:19:9
    at callback (/home/g/scuttlebot/node_modules/pull-pushable/index.js:85:5)
    at Function.push (/home/g/scuttlebot/node_modules/pull-pushable/index.js:44:7)
    at notify (/home/g/scuttlebot/node_modules/pull-notify/index.js:10:20)
```
I'll run it again and see if I can get it to finish syncing. I'll update here either way.

**Comment by evbogue** [comment]
Ok, I just stole @gwenbell's computer and tried this myself because I was tired of watching the sync fail for her.

I deleted her `.ssb/flume` folder, and attempted to resync from scratch. The re-sync works for awhile, and then ends up with the `Cannot read property '0' of undefined` error that you can see above. Once you get to this point, it just fails over and over with same error.

It turns out I wasn't much use here, even after stealing @gwenbell's computer to try to help her.

I could probably back up to an old version of scuttlebot, and resync from there. But I think we have a current issue with first time syncing, if what I'm experiencing right now can replicated elsewhere.

**Comment by evbogue** [comment]
I'm making a little progress after restricting replication to 1 hop. Now all I'm getting is `call stack exceeded` on occasion. Almost finished...

**Comment by gwenbell** [comment]
Sync successful by restricting to one hop out. Got a few more call stack exceeded messages, but eventually it went through.

**Comment by mmckegg** [comment]
@dominictarr looks like there's a bug in `ssb-friends`.

Somehow a `null` object is getting passed into [`isCloser`](https://github.com/ssbc/ssb-friends/blob/master/block.js#L16)

**Comment by evbogue** [comment]
I just got this one too!

It happened when I tried syncing from 1 hop out to 2 hops out with a new db.

```
/home/ev/minbase/node_modules/ssb-friends/block.js:16
  if(then[0] != null && now[0] != null && now[0] < then[0])
         ^

TypeError: Cannot read property '0' of undefined
    at isCloser (/home/ev/minbase/node_modules/ssb-friends/block.js:16:10)
    at Object.exports.update (/home/ev/minbase/node_modules/ssb-friends/block.js:23:6)
    at Object.exports.diffReachable (/home/ev/minbase/node_modules/ssb-friends/alg.js:81:12)
    at /home/ev/minbase/node_modules/ssb-friends/index.js:94:25
    at /home/ev/minbase/node_modules/pull-flatmap/index.js:10:17
    at /home/ev/minbase/node_modules/pull-stream/throughs/filter.js:17:11
    at /home/ev/minbase/node_modules/pull-stream/throughs/through.js:19:9
    at callback (/home/ev/minbase/node_modules/pull-pushable/index.js:85:5)
    at Function.push (/home/ev/minbase/node_modules/pull-pushable/index.js:44:7)
    at notify (/home/ev/minbase/node_modules/flumeview-reduce/node_modules/pull-notify/index.js:10:20)
```

**Comment by mmckegg** [comment]
I haven't yet found this, but I am worried about rolling out a patchwork version using `ssb-friends` with a bug like that on the loose. 😢 

@evbogue does this happen every time? Can you give me a complete list of everything you did since creating a feed to experience this?

**Comment by evbogue** [comment]
@mmckegg Once this happens, it happens every time you start sbot and is unrecoverable unless you sync from scratch. I haven't had much time to investigate, but I'd also hesitate to roll out the latest ssb-friends into Patchwork. 

This most recent time occurred because I had created a new flumedb to test `ooo` in minbase while only syncing one hop out. When I tried going two hops out, at some point during the sync sbot quit out with this error (and then wouldn't recover). 

Could this have something to do with the re-write of validation in secure-scuttlebutt? I think that hit master, right?

**Comment by uhlhosting** [comment]
I am also not able to deploy on CenOS 7 SSBC-PUB

**Comment by mmckegg** [comment]
@evbogue This looks more likely to have been caused by @dominictarr rewriting `ssb-friends` last week. 

`%9mmssBHoGx3Et7zJYg+0+U3gW5klDIxqchjqVDGtgDU=.sha256`

https://github.com/ssbc/ssb-friends/commits/master

**Comment by mmckegg** [comment]
An issue was just opened for this latest bug directly on `ssb-friends`. 

https://github.com/ssbc/ssb-friends/issues/6

I suggest we close this issue (since the original flume bug has been fixed) and continue it [there](https://github.com/ssbc/ssb-friends/issues/6).

**Comment by evbogue** [comment]
@mmckegg I want to keep this issue open, as I'm now getting several other issues that are different from the one @cryptix mentioned in ssb-friends.

I've had to stop using `ssb-ebt` and `ssb-ooo` because they are no longer working for me because of the errors I'm getting, so I had to turn them off.

**Comment by evbogue** [comment]
These errors can be slightly different. Here's the first one:

```
Connected wx.larpa.net:8008:@DTNmX+4SjsgZ7xyDh5xxmNtFqa6pWi5Qtw7cE8aR9TQ=.ed25519
****************************...................... (indexes:100%, ebt:55.800000000000004%)
/home/ev/scuttlebot/node_modules/flumelog-offset/inject.js:78
      frame.getMeta(offset, function (err, value) {
                                     ^

RangeError: Maximum call stack size exceeded
    at /home/ev/scuttlebot/node_modules/flumelog-offset/inject.js:78:38
    at /home/ev/scuttlebot/node_modules/flumelog-offset/frame/recoverable.js:48:11
    at /home/ev/scuttlebot/node_modules/aligned-block-file/blocks.js:72:11
    at get (/home/ev/scuttlebot/node_modules/aligned-block-file/blocks.js:28:7)
    at next (/home/ev/scuttlebot/node_modules/aligned-block-file/blocks.js:51:7)
    at Object.read (/home/ev/scuttlebot/node_modules/aligned-block-file/blocks.js:75:7)
    at next (/home/ev/scuttlebot/node_modules/flumelog-offset/frame/recoverable.js:47:16)
    at /home/ev/scuttlebot/node_modules/flumelog-offset/frame/recoverable.js:43:11
    at /home/ev/scuttlebot/node_modules/aligned-block-file/blocks.js:93:11
    at get (/home/ev/scuttlebot/node_modules/aligned-block-file/blocks.js:28:7)
```
Scuttlebot quits out on this error, upon connecting to an `ssb-ebt` compatible pub.

**Comment by dominictarr** [comment]
@gwenbell @evbogue I think I've fixed that ssb-friends problem. update to ssb-friends@2.3.5

**Comment by evbogue** [comment]
@dominictarr Yes, fixed! I got the `TypeError: Cannot read property '0' of undefined` error again, and then upgraded to `ssb-friends@2.3.5` and scuttlebot started as normal.

**Comment by evbogue** [comment]
Except now avatars aren't ever resolving, in minbase at least. No errors to report, `ssb-avatar` just doesn't ever finish.

**Comment by evbogue** [comment]
avatars not loading might be a different issue. I just realized I upgraded to Node 9.2.0 in my latest `pacman -Syu`

**Comment by evbogue** [comment]
Ok, sorry everyone for the confusion. While `ssb-avatar` is no longer working for me, I do not think it is related to this issue or to the Node.js version. We can close flume-stuck, and I will open an issue on `ssb-avatar` if this issue persists.
