### ISSUE TITLE
Can not setup a pub with ssb-server

### ISSUE THREAD

**Issue by Chuck52** [ssbc/ssb-server#710]
We want to setup a pub on a cloud server to create invite codes for Manyserver.
Now this is problem:
Command list :
   1. npm install -g ssb-server
   2. ssb-server start --logging.level info --port 7002 --host 0.0.0.0
   3. ssb-server --host 0.0.0.0 --port 7002 plugins.install ssb-peer-invites
   4. change ' "name": "ssb-peer-invites" ' to ' " name": "peer-invites" ' in ~/.ssb/config (otherwise ssb-server can not work)
  5. ssb-server start --logging.level info --port 7002 --host 0.0.0.0 (restart)
  6. ssb-server --host 0.0.0.0 --port 7002 peerInvites.create --private 'private msg' --reveal 'test msg'

then we got error message :

> [gotest@transport01 ~]$ ssb-server --host 0.0.0.0 --port 7002 peerInvites.create --private 'private msg' --reveal 'test msg'
> 
> /home/gotest/ssb-server/node-v10.18.0-linux-x64/lib/node_modules/ssb-server/node_modules/muxrpcli/index.js:125
>       throw err
>       ^
> TypeError: Cannot read property 'getState' of undefined
>     at Object.invites.getNearbyPubs (/home/gotest/.ssb/node_modules/ssb-peer-invites/index.js:282:24)
>     at Object.invites.create (/home/gotest/.ssb/node_modules/ssb-peer-invites/index.js:366:15)
>     at Object.hooked (/home/gotest/ssb-server/node-v10.18.0-linux-x64/lib/node_modules/ssb-server/node_modules/hoox/index.js:10:15)
>     at Object.localCall (/home/gotest/ssb-server/node-v10.18.0-linux-x64/lib/node_modules/ssb-server/node_modules/muxrpc/local-api.js:31:29)
>     at Object.<anonymous> (/home/gotest/ssb-server/node-v10.18.0-linux-x64/lib/node_modules/ssb-server/node_modules/muxrpc/local-api.js:37:22)
>     at Object.request (/home/gotest/ssb-server/node-v10.18.0-linux-x64/lib/node_modules/ssb-server/node_modules/muxrpc/stream.js:48:17)
>     at PacketStream._onrequest (/home/gotest/ssb-server/node-v10.18.0-linux-x64/lib/node_modules/ssb-server/node_modules/packet-stream/index.js:161:17)
>     at PacketStream.write (/home/gotest/ssb-server/node-v10.18.0-linux-x64/lib/node_modules/ssb-server/node_modules/packet-stream/index.js:134:41)
>     at /home/gotest/ssb-server/node-v10.18.0-linux-x64/lib/node_modules/ssb-server/node_modules/muxrpc/pull-weird.js:56:15
>     at /home/gotest/ssb-server/node-v10.18.0-linux-x64/lib/node_modules/ssb-server/node_modules/pull-stream/sinks/drain.js:24:37

what else can we do to create a invite code which Manyserver can use on mobile phone?

**Comment by dominictarr** [comment]
you shouldn't need to set `--host 0.0.0.0` do you have an unusual setup here? is there a reason you can't use the default ports. At least, I'd recommend just using the defaults until it's working so there is less to debug.

btw, the propper way to configure the networking is described here: https://github.com/ssbc/ssb-config#connections

you should be able to skip step 4 entirely.
according to ssb-peer-invites readme, you also need `ssb-device-address` and `ssb-identities`.

```
sbot plugins.install ssb-device-address
sbot plugins.install ssb-identities
sbot plugins.install ssb-peer-invites
```
that is why [this line](https://github.com/ssbc/ssb-peer-invites/blob/master/index.js#L282) was erroring.

**Comment by Chuck52** [comment]
already install  plugin ssb-device-address and ssb-identities

if I skip step 4 ,there will be error:

> ssb-server 15.2.0 /home/gotest/.ssb logging.level:info
> my key ID: 8G07HIppZpZX0UJEiMgPkFJRuzLK77OvlafJaL3hTR4=.ed25519
> /home/gotest/ssb-server/node-v10.18.0-linux-x64/lib/node_modules/ssb-server/node_modules/ssb-plugins/load-user-plugins.js:54
>         throw new Error('plugin at:'+module_name+' expected name:'+name+' but had:'+(plugin||{}).name)
>         ^
> 
> Error: plugin at:ssb-device-address expected name:ssb-device-address but had:device-address
>     at module.exports (/home/gotest/ssb-server/node-v10.18.0-linux-x64/lib/node_modules/ssb-server/node_modules/ssb-plugins/load-user-plugins.js:54:15)
>     at Object.module.exports.loadUserPlugins (/home/gotest/ssb-server/node-v10.18.0-linux-x64/lib/node_modules/ssb-server/node_modules/ssb-plugins/index.js:240:55)
>     at Object.<anonymous> (/home/gotest/ssb-server/node-v10.18.0-linux-x64/lib/node_modules/ssb-server/bin.js:65:26)
>     at Module._compile (internal/modules/cjs/loader.js:778:30)
>     at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
>     at Module.load (internal/modules/cjs/loader.js:653:32)
>     at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
>     at Function.Module._load (internal/modules/cjs/loader.js:585:3)
>     at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
>     at startup (internal/bootstrap/node.js:283:19)

after 3 plugins installed , i do step 4, 5,6 again this time and got this :

> [gotest@transport01 ssb-server]$ ssb-server --host 0.0.0.0 --port 7002 peerInvites.create --private 'private msg' --reveal 'test msg'
> 
> /home/gotest/ssb-server/node-v10.18.0-linux-x64/lib/node_modules/ssb-server/node_modules/muxrpcli/index.js:125
>       throw err
>       ^
> Error: failed to find any suitable pubs
>     at /home/gotest/.ssb/node_modules/ssb-peer-invites/index.js:371:21
>     at next (/home/gotest/.ssb/node_modules/ssb-peer-invites/index.js:345:30)
>     at drain (/home/gotest/.ssb/node_modules/ssb-peer-invites/node_modules/pull-paramap/index.js:23:11)
>     at /home/gotest/.ssb/node_modules/ssb-peer-invites/node_modules/pull-paramap/index.js:37:11
>     at /home/gotest/.ssb/node_modules/ssb-peer-invites/node_modules/pull-stream/sources/values.js:19:7
>     at /home/gotest/.ssb/node_modules/ssb-peer-invites/node_modules/pull-paramap/index.js:33:7
>     at /home/gotest/.ssb/node_modules/ssb-peer-invites/node_modules/looper/index.js:11:9
>     at /home/gotest/.ssb/node_modules/ssb-peer-invites/node_modules/pull-paramap/index.js:62:22
>     at /home/gotest/.ssb/node_modules/ssb-peer-invites/index.js:344:13
>     at pull (/home/gotest/.ssb/node_modules/ssb-peer-invites/node_modules/pull-stream/pull.js:41:14)

**Comment by dominictarr** [comment]
@Chuck52 okay I see how the plugins name was happening. I've fixed that in ssb-plugins@1.0.4 you can either reinstall `npm ssb-server -g`. Or, instead of updating the code, you can just remove the name from the object

``` js
"ssb-device-address": {
  "name": "ssb-device-address",//delete this line!
}
```

The second problem, "failed to find nearby pubs": this is a brand new pub, right?
you've made me realize that the documentation isn't clear for what you are trying to do here,
create a new pub set up for peer-invites. peer-invites are intended to be created from ordinary peers, not from pubs. To set up new `peer-invites` pub for the first time, it needs to announce a public address, [follow instructions on ssb-device-address](https://github.com/ssbc/ssb-device-address#usage) and then the pub needs to follow at least one peer, i.e. the ssb-server on your laptop. to follow them manually get the id of the other peer `ssb-server whoami` will output it (or look in `~/.ssb/secret` then

``` bash
ssb-server publish --type contact --contact <@{peer_id}.ed25519> --following
```

or you can use `ssb-server invites.create` from the pub. while answering your question I discovered that `patchbay` is currently the only client ui that supports peer-invites unfortunately, (though there is a [PR for peer-invites in patchwork](https://github.com/ssbc/patchwork/pull/1068)) so you should probably just use [ssb-invite](https://github.com/ssbc/ssb-invite) for now.

**Comment by Chuck52** [comment]
still failed with ssb-peer-invites,then i try to use ssb-invite instead. 
Command list :

> npm install -g ssb-server

> ssb-server start --logging.level info --port 7002

then i found command invite not exists ,like this :

> [gotest@transport01 ~]$ ssb-server --host 0.0.0.0 --port 7002 invite
> { cmd: [], help: [ 'invite' ] }
> missing command: invite
> createLogStream|get|publish|add|status|progress|version|whoami|createHistoryStream
> plugins # manage ssb plugins
> gossip # keep track of peers, and decide when to connect to them
> friends # track what feeds are following or blocking each other
> blobs # retrive, store, and share blobs
> query # query ssb database with map-filter-reduce queries
> ooo # gossip ssb messages without replicating the entire feed, aka "Out of Order"

then i run 'ssb-server plugins.install ssb-invite' and restart,got this:

> [gotest@transport01 ssb-server]$ ./start.sh 
> ssb-server 15.2.0 /home/gotest/.ssb logging.level:info
> my key ID: 3m8RTrMGDmjpYauNx/sAzOCOpKFl77klOglZYWzZ5To=.ed25519
> plugin named:invite is already loaded, skipping
> ssb-friends: stream legacy api used

and command invite also not exists

**Comment by dominictarr** [comment]
`ssb-server invite.create` not `invite.
`ssb-invite` [comes installed](https://github.com/ssbc/ssb-server/blob/master/bin.js#L55), so you don't need to install it.

btw, I'd recommend putting the host and port in the `~/.ssb/config` file instead of passing it every time.

**Comment by Chuck52** [comment]
> [gotest@transport01 ~]$ ssb-server --host 0.0.0.0 --port 7002 invite.create 1
> 
> /home/gotest/ssb-server/node-v10.18.0-linux-x64/lib/node_modules/ssb-server/node_modules/muxrpcli/index.js:125
>       throw err
>       ^
> TypeError: cb is not a function
>     at Object.<anonymous> (/home/gotest/ssb-server/node-v10.18.0-linux-x64/lib/node_modules/ssb-server/node_modules/ssb-invite/index.js:108:18)
>     at apply (/home/gotest/ssb-server/node-v10.18.0-linux-x64/lib/node_modules/ssb-server/node_modules/muxrpc-validation/index.js:199:15)
>     at Object.<anonymous> (/home/gotest/ssb-server/node-v10.18.0-linux-x64/lib/node_modules/ssb-server/node_modules/muxrpc-validation/index.js:86:14)
>     at Object.hooked (/home/gotest/ssb-server/node-v10.18.0-linux-x64/lib/node_modules/ssb-server/node_modules/hoox/index.js:10:15)
>     at Object.localCall (/home/gotest/ssb-server/node-v10.18.0-linux-x64/lib/node_modules/ssb-server/node_modules/muxrpc/local-api.js:31:29)
>     at Object.<anonymous> (/home/gotest/ssb-server/node-v10.18.0-linux-x64/lib/node_modules/ssb-server/node_modules/muxrpc/local-api.js:37:22)
>     at Object.request (/home/gotest/ssb-server/node-v10.18.0-linux-x64/lib/node_modules/ssb-server/node_modules/muxrpc/stream.js:48:17)
>     at PacketStream._onrequest (/home/gotest/ssb-server/node-v10.18.0-linux-x64/lib/node_modules/ssb-server/node_modules/packet-stream/index.js:161:17)
>     at PacketStream.write (/home/gotest/ssb-server/node-v10.18.0-linux-x64/lib/node_modules/ssb-server/node_modules/packet-stream/index.js:134:41)
>     at /home/gotest/ssb-server/node-v10.18.0-linux-x64/lib/node_modules/ssb-server/node_modules/muxrpc/pull-weird.js:56:15

i know what you say,but the invite command is missing

> [gotest@transport01 ~]$ ssb-server --host 0.0.0.0 --port 7002 invite
> { cmd: [], help: [ 'invite' ] }
> missing command: invite

**Comment by dominictarr** [comment]
@Chuck52 there is no invite command. invite is a _group_ of commands. it's always `ssb-server {group}.{command}`

The other problem is that you are passing --host and --port (I told you to set it in the config) arguments passed to ssb-server like that are interpreted as arguments to _the command_, iirc. to pass them to the config, you need `ssb-server invite.create 1 -- --host 0.0.0.0 --port 7002`

**Comment by Chuck52** [comment]
OK,this works. then got this:

> [gotest@transport01 ssb-server]$ ssb-server invite.create 1
> 
> /home/gotest/ssb-server/node-v10.18.0-linux-x64/lib/node_modules/ssb-server/node_modules/muxrpcli/index.js:125
>       throw err
>       ^
> Error: Server has no public ip address, cannot create useable invitation
>     at Object.<anonymous> (/home/gotest/ssb-server/node-v10.18.0-linux-x64/lib/node_modules/ssb-server/node_modules/ssb-invite/index.js:108:21)
>     at apply (/home/gotest/ssb-server/node-v10.18.0-linux-x64/lib/node_modules/ssb-server/node_modules/muxrpc-validation/index.js:197:15)
>     at Object.<anonymous> (/home/gotest/ssb-server/node-v10.18.0-linux-x64/lib/node_modules/ssb-server/node_modules/muxrpc-validation/index.js:86:14)
>     at Object.hooked (/home/gotest/ssb-server/node-v10.18.0-linux-x64/lib/node_modules/ssb-server/node_modules/hoox/index.js:10:15)
>     at Object.localCall (/home/gotest/ssb-server/node-v10.18.0-linux-x64/lib/node_modules/ssb-server/node_modules/muxrpc/local-api.js:31:29)
>     at Object.<anonymous> (/home/gotest/ssb-server/node-v10.18.0-linux-x64/lib/node_modules/ssb-server/node_modules/muxrpc/local-api.js:37:22)
>     at Object.request (/home/gotest/ssb-server/node-v10.18.0-linux-x64/lib/node_modules/ssb-server/node_modules/muxrpc/stream.js:48:17)
>     at PacketStream._onrequest (/home/gotest/ssb-server/node-v10.18.0-linux-x64/lib/node_modules/ssb-server/node_modules/packet-stream/index.js:161:17)
>     at PacketStream.write (/home/gotest/ssb-server/node-v10.18.0-linux-x64/lib/node_modules/ssb-server/node_modules/packet-stream/index.js:134:41)
>     at /home/gotest/ssb-server/node-v10.18.0-linux-x64/lib/node_modules/ssb-server/node_modules/muxrpc/pull-weird.js:56:15

but this is a cloud server with public ip.

**Comment by cryptix** [comment]
@Chuck52 there is an (sadly) [undocumented config option](https://github.com/ssbc/ssb-invite/blob/master/index.js#L68) for invite to allow private IP addresses for invite creation. 

Adding this to `~/.ssb/config` and restarting ssb-server should do the trick. You just have to replace the IP for the real/public one after it was created.

```json
{
  "invite": {
    "allowPrivate": true
  }
}
```

HTH

**Comment by nkbai** [comment]
the following is my config 
```
{
  "plugins": {
    "ssb-device-address": {
    },
    "ssb-peer-invites": {
      "name": "peer-invites"
    },
"invite":{
"allowPrivate":true
}
  }
}
```
after I run command ` sbot invite.create --allow-private 1`, the server failed and cannot start again.

thanks.

```
ssb-server 15.2.0 /home/bai/.ssb logging.level:notice
my key ID: Spb+nYjGa4XBFWMqPVtF5eqDvQt6Spkl6ebrU3Fj2rk=.ed25519
internal/modules/cjs/loader.js:583
    throw err;
    ^

Error: Cannot find module '/home/bai/.ssb/node_modules/invite'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
    at Function.Module._load (internal/modules/cjs/loader.js:507:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at module.exports (/home/bai/test/node-v10.11.0-linux-x64/lib/node_modules/ssb-server/node_modules/ssb-plugins/load-user-plugins.js:50:18)
    at Object.module.exports.loadUserPlugins (/home/bai/test/node-v10.11.0-linux-x64/lib/node_modules/ssb-server/node_modules/ssb-plugins/index.js:240:55)
    at Object.<anonymous> (/home/bai/test/node-v10.11.0-linux-x64/lib/node_modules/ssb-server/bin.js:65:26)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)

```

**Comment by keks** [comment]
@nkbai In your config, the `invite` is inside the `plugins` object, but needs to be top-level.

**Comment by nkbai** [comment]
my server is running on tencent clound, and i still cannot run this app

```
bai@t1:~/.ssb$ sbot invite.create --allow-private 1

/home/bai/test/node-v10.11.0-linux-x64/lib/node_modules/ssb-server/node_modules/muxrpcli/index.js:125
      throw err
      ^
Error: Server has no public ip address, cannot create useable invitation
    at Object.<anonymous> (/home/bai/test/node-v10.11.0-linux-x64/lib/node_modules/ssb-server/node_modules/ssb-invite/index.js:108:21)
    at apply (/home/bai/test/node-v10.11.0-linux-x64/lib/node_modules/ssb-server/node_modules/muxrpc-validation/index.js:197:15)
    at Object.<anonymous> (/home/bai/test/node-v10.11.0-linux-x64/lib/node_modules/ssb-server/node_modules/muxrpc-validation/index.js:86:14)
    at Object.hooked (/home/bai/test/node-v10.11.0-linux-x64/lib/node_modules/ssb-server/node_modules/hoox/index.js:10:15)
    at Object.localCall (/home/bai/test/node-v10.11.0-linux-x64/lib/node_modules/ssb-server/node_modules/muxrpc/local-api.js:31:29)
    at Object.<anonymous> (/home/bai/test/node-v10.11.0-linux-x64/lib/node_modules/ssb-server/node_modules/muxrpc/local-api.js:37:22)
    at Object.request (/home/bai/test/node-v10.11.0-linux-x64/lib/node_modules/ssb-server/node_modules/muxrpc/stream.js:48:17)
    at PacketStream._onrequest (/home/bai/test/node-v10.11.0-linux-x64/lib/node_modules/ssb-server/node_modules/packet-stream/index.js:161:17)
    at PacketStream.write (/home/bai/test/node-v10.11.0-linux-x64/lib/node_modules/ssb-server/node_modules/packet-stream/index.js:134:41)
    at /home/bai/test/node-v10.11.0-linux-x64/lib/node_modules/ssb-server/node_modules/muxrpc/pull-weird.js:56:15
```

**Comment by keks** [comment]
@nkbai Can you post your config? Either the server is not properly configured or ssb-server internally overrides the configuration. That error message you post is created [here](https://github.com/ssbc/ssb-invite/blob/57e7cdd7393000cf2ae51c5e88439ebb24d4813d/index.js#L101:L104), and that wouldn't happen if `config.allowPrivate` was set.

**Comment by cryptix** [comment]
Ah.. damn.. the plugin name key in the config might need to be `ssb-invite` not just `invite`..

**Comment by dominictarr** [comment]
@nkbai if it's a cloud server with a public address, do not set a host option, it will detect it's own public ip address and create an invite with that address. The invite needs to have the correct address in it, because the guest will need to connect to that. (as I suggested in https://github.com/ssbc/ssb-server/issues/710#issuecomment-570509804 it's easier to use the defaults and get it working, then change it after)

> ps: it might also work as `ssb-server invite.create --allow-private 1` but I'm not sure.

@cryptix this is incorrect. You can set config options on the cli, but they will only be server options if they are passed to `ssb-server start {options}` you can set any option, but it must follow the correct syntax.
To set `"invite": {"allowPrivate": true}` you'd do `--invite.allowPrivate` see [rc](https://github.com/dominictarr/rc/) documentation. Anyway, allowPrivate is really just for testing. The correct solution is to allow the server to detect it's own ip address (or set it to the correct ip, not 0.0.0.0)

**Comment by Chuck52** [comment]
it works. thanks a lot!

> [gotest@transport01 ~]$ ssb-server invite.create 500
> "0.0.0.0:7002:@3m8RTrMGDmjpYauNx/sAzOCOpKFl77klOglZYWzZ5To=.ed25519~JRm+GnkKVqIO6sxkKl7SxCBP1ugE8XkWs2jeLmHM2Kk="
